---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-pv
  namespace: n8n-project
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/c/Users/cmolina/Desktop/varios/k8s-n8n/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: n8n-project
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/c/Users/cmolina/Desktop/varios/k8s-n8n/postgres-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
  namespace: n8n-project
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi